// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebSocketChatWithLoginNew.Models;

public partial class Message
{
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int MesIdpk { get; set; }

    public string MesMessage { get; set; }

    public DateTime MesTimeSent { get; set; }

    public DateTime? MesTimeEdited { get; set; }

    public DateTime? MesTimeDeleted { get; set; }

    public string MesUserIdfk { get; set; }

    public virtual AspNetUser MesUserIdfkNavigation { get; set; }
}